data :
  root_dir : "./data/SPOKEN"
  train_orig_txt : ['/home/taesoo/GEC/data/SPOKEN/original_train.txt']
  train_corrupt_txt : ['/home/taesoo/GEC/data/SPOKEN/corrupted_train.txt']
  val_orig_txt : ['/home/taesoo/GEC/data/SPOKEN/original_val.txt']
  val_corrupt_txt : ['/home/taesoo/GEC/data/SPOKEN/corrupted_val.txt']

model_config:
  max_len : 128
  critic :
    pretrained_model : "monologg/koelectra-base-v3-discriminator"
  generator :
    pretrained_model : "monologg/koelectra-base-v3-generator"
  
train_config :
  n_epochs : 1000
  batch_size : 32
  lr : 2e-5